print("before appending data - - - - -")
f = open("test.txt","r")
content = f.read()
print(content)
f.close()
f = open("test.txt","a")
f.write("Python is amazing")
f.write("\n Python is cool")
f.write("\n Python is easy and simple to learn")
f.close()
print("After appending data - - - - -")
f = open("test.txt","r")
content = f.read()
print(content)
f.close()